/**
 * A single line of world history. These are generated by the simulation and by
 * live gameplay, persisted forever, and replayed on the "WHILE YOU WERE DEAD"
 * screen and in the chronicle.
 */

export type WorldEventType =
  | 'duel'
  | 'promotion'
  | 'demotion'
  | 'betrayal'
  | 'alliance'
  | 'assassination'
  | 'injury'
  | 'territory'
  | 'revenge'
  | 'recruitment'
  | 'mutation'
  | 'resurrection'
  | 'weapon_theft'
  | 'death'
  | 'birth'
  | 'player_kill'
  | 'player_death'
  | 'player_spared'
  | 'player_escape'
  | 'enemy_escape'
  | 'overlord_slain'
  | 'age_begins'
  | 'succession'
  | 'vendetta'
  | 'humiliation'
  | 'bargain'
  | 'extraction'
  | 'heat'
  | 'feral_incident'
  | 'dungeon_delved'
  | 'dungeon_cleared'
  | 'dungeon_reopened'
  | 'quest_complete'
  | 'biome_gather';

/** Facts that cannot be recovered from the display sentence. */
export interface WorldEventPayload {
  areaId?: string;
  rankFrom?: string;
  rankTo?: string;
  itemName?: string;
  itemKind?: string;
  weaponId?: string;
  instanceId?: string;
  recoveredFrom?: string;
  cause?: string;
  scarId?: string;
  vendettaState?: 'started' | 'complete' | 'failed';
}

export interface WorldEvent {
  turn: number;
  age: number;
  type: WorldEventType;
  /** already-rendered uppercase sentence, e.g. "VARK DEFEATED GRIM." */
  text: string;
  /** nemesis ids involved, first is the primary actor */
  actors: string[];
  /** shown on the death report with emphasis */
  important: boolean;
  /** styling hint for the UI */
  tone?: 'neutral' | 'bad' | 'good' | 'gold';
  /** stable id; assigned on log for new events, migrated for old saves */
  id?: string;
  /** player-meta run index when the event happened, if known */
  runId?: number;
  /** the player was present when this occurred */
  witnessed?: boolean;
  /** the player has been told this happened (death report, chronicle, scouting) */
  known?: boolean;
  payload?: WorldEventPayload;
}

const PLAYER_FACING: Set<WorldEventType> = new Set([
  'player_kill',
  'player_death',
  'player_spared',
  'player_escape',
  'enemy_escape',
  'extraction',
  'vendetta',
  'overlord_slain',
  'humiliation',
  'bargain',
  'heat',
]);

export function isPlayerFacingEvent(type: WorldEventType): boolean {
  return PLAYER_FACING.has(type);
}

export function makeEvent(
  turn: number,
  age: number,
  type: WorldEventType,
  text: string,
  actors: string[] = [],
  important = false,
  tone: WorldEvent['tone'] = 'neutral',
  extra?: Partial<Pick<WorldEvent, 'id' | 'runId' | 'witnessed' | 'known' | 'payload'>>
): WorldEvent {
  const witnessed = extra?.witnessed ?? isPlayerFacingEvent(type);
  return {
    turn,
    age,
    type,
    text: text.toUpperCase(),
    actors,
    important,
    tone,
    witnessed,
    known: extra?.known ?? witnessed,
    id: extra?.id,
    runId: extra?.runId,
    payload: extra?.payload,
  };
}
