/**
 * A single line of world history. These are generated by the simulation and by
 * live gameplay, persisted forever, and replayed on the "WHILE YOU WERE DEAD"
 * screen and in the chronicle.
 */

export type WorldEventType =
  | 'duel'
  | 'promotion'
  | 'demotion'
  | 'betrayal'
  | 'alliance'
  | 'assassination'
  | 'injury'
  | 'territory'
  | 'revenge'
  | 'recruitment'
  | 'mutation'
  | 'resurrection'
  | 'weapon_theft'
  | 'death'
  | 'birth'
  | 'player_kill'
  | 'player_death'
  | 'player_spared'
  | 'player_escape'
  | 'enemy_escape'
  | 'overlord_slain'
  | 'age_begins'
  | 'succession';

export interface WorldEvent {
  turn: number;
  age: number;
  type: WorldEventType;
  /** already-rendered uppercase sentence, e.g. "VARK DEFEATED GRIM." */
  text: string;
  /** nemesis ids involved, first is the primary actor */
  actors: string[];
  /** shown on the death report with emphasis */
  important: boolean;
  /** styling hint for the UI */
  tone?: 'neutral' | 'bad' | 'good' | 'gold';
}

export function makeEvent(
  turn: number,
  age: number,
  type: WorldEventType,
  text: string,
  actors: string[] = [],
  important = false,
  tone: WorldEvent['tone'] = 'neutral'
): WorldEvent {
  return { turn, age, type, text: text.toUpperCase(), actors, important, tone };
}
